---
abstract: 'run ./Build runtest on the build distribution'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-TestRun
provides:
  Dist::Zilla::Plugin::TestRun:
    file: lib/Dist/Zilla/Plugin/TestRun.pm
    version: v0.0.2
requires:
  Dist::Zilla::Role::TestRunner: 0
  Moose: 0
  perl: 5.012
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-TestRun
  repository: git://github.com/shlomif/perl-Dist-Zilla-Plugin-TestRun.git
version: 0.0.2
